llm:
  model: gpt-4.1-nano-2025-04-14
  temperature: 0.1

embedding:
  model: text-embedding-3-large
  batch_size: 100

indexing:
  chunk_size: 4096
  text_splitter: sentence
  similarity_top_k: 4
  response_mode: refine

storage:
  persist_dir: storage

data:
  source_dir: data
